config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'welcome/index'

  get 'welcome/about'
  
  root 'welcome#index'
  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end




#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

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    #devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit( :email, :password, :password_confirmation) }
    devise_parameter_sanitizer.permit(:sign_in) { |u| u.permit( :email, :password ) }
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:email, :password, :password_confirmation, :current_password) }
  end
  
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bloc-It-Off</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

 <% if user_signed_in? %>
   Signed in as: <strong><%= current_user.email %></strong> |
   <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> - <%= link_to "Sign Out", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
 <% else %>
   <%= link_to "Sign Up", new_user_registration_path, :class => 'navbar-link'  %> -
   <%= link_to "Sign In", new_user_session_path, :class => 'navbar-link'  %> 
 <% end %>
 
 
  <ul>
    <div class="container">
      <ul class="nav nav-tabs">
        <li><%= link_to "Home", welcome_index_path %></li>
        <li><%= link_to "About", "/welcome/about" %></li> 
      </ul>
    </div>
  </ul>
  

 <% flash.each do |key, value| %>
     <div class = "alert alert-<%=key %>"><%=value%></div>
 <% end %>
 
 <%= yield %>
  
</body>
</html>

app/views/welcome/about.html.erb
<div class="container">
  <h1>About Bloc-It-Off:</h1>
  <h2>Created by: Robert Aguirre</h2>
</div>

app/views/welcome/index.html.erb
<br>
<div class="jumbotron text-center">
  <h1>Welcome to Bloc-It-Off</h1>
    <p>The self Destructing To Do Application to prioritize your life</p>
    <p>Don't just block notes, Bloc-it-off!</p>
</div>